<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a500a0a757365722e70726f746f12076d65737361676522310a0455736572120a0a02696418012001280d12100a08757365726e616d65180220012809120b0a0361676518032001280d620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

